### ISSUE TITLE
vse na enem kupi :) 

### ISSUE THREAD

**Issue by Hlupkoo** [CareKajze/ClickyBall#13]
### buge: - ko žoga padne dol pa že zgubiš še jo vedno lahko dvignes, pa stisnes 1x
                 - včasih ko stisneš na žogo, pa jo odnese malo po svoje
                 - včasih se vrti včasih ne samo mene to nemoti

Drugač spremeno nebi nič drastičnega razn to, da bi blo ful vredi odzadi namesto plota kaki motiv stadiona, namesto muzike zvok navijačov, mogoče v nadaljevanju pri določenem scori nove barve žog, pa miška da bi naredo kopačko, al pa neke drugiga samo ne tote bele miške drugač pa pohvalno, pa na tleh naj bo trava za fuzbal (igrišče) ne pa travnika. Pa ko narediš novi rekord bi lahko blo to bol izpostavleno oz. napisano negi. Pa meni ko mas tam malo namajnse slabo vidim slep pa nisem apak okej drugač pa je kul :+1:

**Comment by CareKajze** [comment]
Fixed all bugs.

**Comment by CareKajze** [comment]
Added new background, audio, ground.

**Comment by CareKajze** [comment]
Custom cursor added.
