### ISSUE TITLE
Credits: Add few stuff

### ISSUE THREAD

**Issue by CareKajze** [CareKajze/ClickyBall#5]
Need to add special thanks people, MaterialUI and Brackeys to credits scene.

**Comment by Danxiii** [comment]
Plis added difrend balls :D and a new backgraund :3 (like maybe a steidiom or football feld or somting like that :D ) 
and added if its possible that if u get to 20 score that the ball is faster and faster every 20 or some more points :D

**Comment by CareKajze** [comment]
Added.
