### ISSUE TITLE
Sudgestions for the game 

### ISSUE THREAD

**Issue by Danxiii** [CareKajze/ClickyBall#8]
added your sudgestions :D

**Comment by Danxiii** [comment]
Plis added difrend balls :D and a new backgraund :3 (like maybe a steidiom or football feld or somting like that :D ) 
and added if its possible that if u get to 20 score that the ball is faster and faster every 20 or some more points :D

**Comment by Danxiii** [comment]
and can u make a time line :D when u play the game that time is caunting :D

**Comment by Danxiii** [comment]
if u can make that the **mous icon is a football shos** then the game will me more more realistic.

**Comment by Danxiii** [comment]
i think that when u enter the game that u can chus your nickname, and with your nickname u can recenides your score. That so u can se if u are on the score :D that would be greate if u will addet in the game :D

**Comment by CareKajze** [comment]
Added new background, custom cursor.
